# Generated by Django 5.2.8 on 2026-01-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='books_book_title_d3218d_idx',
        ),
        migrations.AddField(
            model_name='author',
            name='name_search',
            field=models.CharField(db_index=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='title_search',
            field=models.CharField(db_index=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='name_search',
            field=models.CharField(db_index=True, default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title_search'], name='books_book_title_s_ae82d5_idx'),
        ),
    ]
