# Generated by Django 5.2.8 on 2026-02-13 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_books_book_title_d3218d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='books_book_downloa_5784d4_idx',
        ),
        migrations.RemoveField(
            model_name='book',
            name='downloads_count',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='book',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='views_count',
        ),
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bookview',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='books.book'),
        ),
        migrations.AddField(
            model_name='bookview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bookview',
            index=models.Index(fields=['book', 'created_at'], name='books_bookv_book_id_179fff_idx'),
        ),
        migrations.AddIndex(
            model_name='bookview',
            index=models.Index(fields=['user', 'created_at'], name='books_bookv_user_id_3894bc_idx'),
        ),
    ]
