# Generated by Django 5.2.8 on 2026-02-13 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookview',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddIndex(
            model_name='bookview',
            index=models.Index(fields=['session_key', 'created_at'], name='books_bookv_session_fe9455_idx'),
        ),
    ]
