# Generated by Django 5.2.8 on 2026-03-12 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_bookview_session_key_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='books_book_title_s_ae82d5_idx',
        ),
        migrations.RemoveField(
            model_name='author',
            name='name_search',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title_search',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='name_search',
        ),
    ]
